version: '2.2'
services:
  db:
    build:
      dockerfile: Dockerfile
      context: postgres
    ports:
      - 5433:5432
    volumes:
      - web_service_tasks_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=web-service-tasks

volumes:
  web_service_tasks_pg_data:
